#!/usr/bin/groovy
@Library('jenkins-pipeline@v0.4.5')
import com.invoca.utils.*;

pipeline {
  agent {
    kubernetes {
      defaultContainer "ruby"
      yamlFile ".jenkins/ruby_build_pod.yml"
    }
  }

  environment {
    GITHUB_TOKEN         = credentials('github_token')
    BUNDLE_GEM__FURY__IO = credentials('gemfury_deploy_token')
  }

  stages {
    stage('Setup') {
      steps {
        updateGitHubStatus('clean-build', 'pending', 'Unit tests.')
        script {
          sh 'bundle install'
          sh 'bundle exec appraisal install'
        }
      }
    }

    stage('Appraisals') {
      parallel {
        stage('Current') {
          steps { sh 'bundle exec rspec --format RspecJunitFormatter --out spec/reports/current/rspec.xml' }
          post  { always { junit 'spec/reports/current/*.xml' } }
        }

        stage('Rails 4') {
          steps { sh 'bundle exec appraisal rails-4 rspec --format RspecJunitFormatter --out spec/reports/rails-4/rspec.xml' }
          post  { always { junit 'spec/reports/rails-4/*.xml' } }
        }

        stage('Rails 5') {
          steps { sh 'bundle exec appraisal rails-5 rspec --format RspecJunitFormatter --out spec/reports/rails-5/rspec.xml' }
          post  { always { junit 'spec/reports/rails-5/*.xml' } }
        }

        stage('Rails 6') {
          steps { sh 'bundle exec appraisal rails-6 rspec --format RspecJunitFormatter --out spec/reports/rails-6/rspec.xml' }
          post  { always { junit 'spec/reports/rails-6/*.xml' } }
        }
      }
    }
  }

  post {
    success { updateGitHubStatus('clean-build', 'success', 'Unit tests.') }
    failure { updateGitHubStatus('clean-build', 'failure', 'Unit tests.') }
  }
}

void updateGitHubStatus(String context, String status, String description) {
  gitHubStatus([
    repoSlug:    'Invoca/monotonic_tick_count',
    sha:         env.GIT_COMMIT,
    description: description,
    context:     context,
    targetURL:   env.RUN_DISPLAY_URL,
    token:       env.GITHUB_TOKEN,
    status:      status
  ])
}
