---
apiVersion: v1
kind: Pod
metadata:
  labels:
  jenkins/monotonic-tick_count: 'true'
  namespace: jenkins
  name: monotonic-tick_count
spec:
  containers:
  - name: ruby
    image: ruby:2.6.5
    tty: true
    resources:
    requests:
      memory: "100Mi"
    command:
      - cat

