---
name: Test
on: [push]
jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6, 2.7, '3.0']
        gemfile:
        - Gemfile
        - gemfiles/rails_4.gemfile
        - gemfiles/rails_5.gemfile
        - gemfiles/rails_6.gemfile
        exclude:
        - ruby: 2.7
          gemfile: gemfiles/rails_4.gemfile
        - ruby: '3.0'
          gemfile: gemfiles/rails_4.gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: 1.17.3
        bundler-cache: true
    - name: Unit tests
      run: bundle exec rspec

